### ISSUE TITLE
Make features for interactive annotations

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/react-msaview#12]

**Comment by cmdcolin** [comment]
See jalview selection UI

We currently have a click-and-drag scroll, which we could either

a) remove the click-and-drag scroll to accomodate click-and-drag selection, and find alternative scroll method e.g. scrollbar like jalview has
b) make click-and-drag selection a particular toggle mode (likely)

**Comment by ihh** [comment]
As well as a toggle mode (or instead of), user could press shift to change click-and-drag behavior from scroll to select?

**Comment by ihh** [comment]
*hold down shift

**Comment by cmdcolin** [comment]
In the most basic form, we could click and drag over the ruler bar to "annotate" a coordinate range in the MSA. This would be in MSA coordinate space.  If needed we could translate back to an individual protein space


Creating the annotation could create an annotation track similar to the now existing uniprot feature tracks.

Then a dialog box could pop giving the user options for notes that want to add. Right idea?

**Comment by ihh** [comment]
Yes I think that makes sense.
I think usually protein space will be more "stable" as a reference frame than MSA coordinate space, especially if we are talking to other components, or imagining these as "persistent" annotations. Although clearly some annotations do arrive in alignment space, e.g. the secondary structures in a Stockholm file, and in an MSA viewer this (columns) is the natural frame to use.

**Comment by cmdcolin** [comment]
Added in #34

**Comment by cmdcolin** [comment]
welcome to try out on https://gmod.github.io/react-msaview

example link with some custom features annotated

https://gmod.github.io/react-msaview/?data=%7B%22msaview%22%3A%7B%22data%22%3A%7B%22tree%22%3A%22%22%7D%2C%22id%22%3A%22D8U7RR_gj%22%2C%22type%22%3A%22MsaView%22%2C%22height%22%3A550%2C%22treeAreaWidth%22%3A400%2C%22treeWidth%22%3A300%2C%22rowHeight%22%3A20%2C%22scrollY%22%3A0%2C%22scrollX%22%3A0%2C%22resizeHandleWidth%22%3A5%2C%22blockSize%22%3A1000%2C%22selectedStructures%22%3A%5B%5D%2C%22labelsAlignRight%22%3Afalse%2C%22colWidth%22%3A16%2C%22showBranchLen%22%3Atrue%2C%22bgColor%22%3Atrue%2C%22drawTree%22%3Atrue%2C%22drawNodeBubbles%22%3Atrue%2C%22highResScaleFactor%22%3A2%2C%22colorSchemeName%22%3A%22maeditor%22%2C%22msaFilehandle%22%3A%7B%22uri%22%3A%22https%3A%2F%2Fihh.github.io%2Fabrowse%2Fbuild%2Fpfam-cov2.stock%22%7D%2C%22currentAlignment%22%3A0%2C%22collapsed%22%3A%5B%5D%2C%22boxTracks%22%3A%5B%5D%2C%22turnedOffTracks%22%3A%7B%7D%2C%22annotatedRegions%22%3A%5B%7B%22start%22%3A39%2C%22end%22%3A70%2C%22attributes%22%3A%7B%22Name%22%3A%5B%22BigGap%22%5D%7D%7D%2C%7B%22start%22%3A43%2C%22end%22%3A46%2C%22attributes%22%3A%7B%22Name%22%3A%5B%22CustomAnnotation%22%5D%2C%22Note%22%3A%5B%22Virulent+region%22%5D%7D%7D%5D%7D%2C%22nglSelection%22%3A%22%22%7D#
