### ISSUE TITLE
PF01601 demo example is broken

### ISSUE THREAD

**Issue by ihh** [GMOD/react-msaview#16]
No alignment or tree visible, sequence names all "Undefined":

![Screen Shot 2021-06-04 at 12 01 46 PM](https://user-images.githubusercontent.com/54113/120850753-b290d080-c52c-11eb-9a90-a2a39d1eb8a5.png)

**Comment by cmdcolin** [comment]
@ihh this should be fixed in https://github.com/GMOD/react-msaview/commit/c33a1c15a214afc44e9283e6d9f511f62b3de641

might be able to refresh page and see it work?

**Comment by cmdcolin** [comment]
probably can close for now. happy to get eyeballs on the app though :)
