### ISSUE TITLE
Fast scrolling gets ahead of the component a bit

### ISSUE THREAD

**Issue by ihh** [GMOD/react-msaview#3]
It catches up eventually but if (for example) I spin the mouse wheel fast to get the the edges of the alignment, I often see blank screen for a few seconds. Is there a reason why it has to blank the screen before redrawing, rather than doing some kind of double-buffering i.e. waiting for the render to complete before switching out the canvas elements?

**Comment by ihh** [comment]
Update: the link in my comment above is now broken and I can't replicate the problem with the "[MAFFT+VeryFastTree(17.9k samples)](https://gmod.github.io/react-msaview/?data=%7B%22msaview%22%3A%7B%22data%22%3A%7B%7D%2C%22id%22%3A%22nKAlNUDONc3QJMCvb2wDU%22%2C%22minimized%22%3Afalse%2C%22type%22%3A%22MsaView%22%2C%22height%22%3A550%2C%22treeAreaWidth%22%3A400%2C%22treeWidth%22%3A300%2C%22rowHeight%22%3A20%2C%22scrollY%22%3A-11775.090209960938%2C%22scrollX%22%3A0%2C%22resizeHandleWidth%22%3A5%2C%22blockSize%22%3A1000%2C%22selectedStructures%22%3A%5B%7B%22id%22%3A%22RDRP_BPPH6%2F35-607%22%2C%22structure%22%3A%7B%22pdb%22%3A%224a8s%22%2C%22startPos%22%3A34%2C%22endPos%22%3A606%7D%7D%5D%2C%22labelsAlignRight%22%3Afalse%2C%22colWidth%22%3A16%2C%22showBranchLen%22%3Atrue%2C%22bgColor%22%3Atrue%2C%22drawTree%22%3Atrue%2C%22drawNodeBubbles%22%3Atrue%2C%22highResScaleFactor%22%3A2%2C%22colorSchemeName%22%3A%22maeditor%22%2C%22treeFilehandle%22%3A%7B%22locationType%22%3A%22UriLocation%22%2C%22uri%22%3A%22https%3A%2F%2Fjbrowse.org%2Fgenomes%2Fmultiple_sequence_alignments%2Frhv_test-only.aligned_with_mafft_auto.nh%22%7D%2C%22msaFilehandle%22%3A%7B%22locationType%22%3A%22UriLocation%22%2C%22uri%22%3A%22https%3A%2F%2Fjbrowse.org%2Fgenomes%2Fmultiple_sequence_alignments%2Frhv_test-only.aligned_with_mafft_auto.fa%22%7D%2C%22currentAlignment%22%3A0%2C%22collapsed%22%3A%5B%5D%2C%22boxTracks%22%3A%5B%5D%2C%22turnedOffTracks%22%3A%7B%7D%2C%22annotatedRegions%22%3A%5B%5D%7D%2C%22nglSelection%22%3A%22%22%7D#) example. Is this problem fixed?

**Comment by cmdcolin** [comment]
I don't know the context of the original issue but it may have been 'fixed' to some degree. if you have screen recordings can check it out but if it feels fixed on your end can close for now.  it may have been that this issue was just due to general slowness and laggyness but it may have been improved since then
