### ISSUE TITLE
Alignment column numbers are unstable and (perhaps?) shouldn't be shown by default

### ISSUE THREAD

**Issue by ihh** [GMOD/react-msaview#39]
The problem with having a "ruler" showing the alignment column numbers is that the number for a particular column changes when tree nodes are expanded or collapsed.

I am not sure what the right way to handle this is. ABrowse simply didn't display column numbers, for this precise reason.

One possibility is to keep column numbers stable, and have gaps in the ruler (i.e. there could be some adjacent columns whose numbers were not consecutive).

Alternatively the ruler could be hidden by default.

Another idea (possibly in combination with a default-hidden ruler) is to warn the user that column numbers are not stable, the first time they collapse a node (while the ruler is visible). Or, have some other text somewhere to alert the user of this (e.g. mouseover tooltip kind of thing)

I suppose there is a counterargument that it's still useful to have a ruler even if it's a fragile ruler, but I think we should warn the user somehow.

**Comment by ihh** [comment]
I do really like the idea of per-row absolute positional variants using something like the Pango lineage naming scheme

https://cov-lineages.org/

**Comment by ihh** [comment]
*absolute coordinates

**Comment by ihh** [comment]
I'm imagining something like

col412.B.1.1.col3.7.col2

which would be interpreted as
- start at column 412 of the root lineage
- Pango-named variant B.1.1 then has an insertion to the right of that position [need to check exactly how Pango defines these phylogenetic paths]. Move to the third residue of this insertion
- Pango-named variant B.1.1.7 then has another insertion to the right of *that* position. Move to the second residue of this later insertion
- this is the column you want

**Comment by ihh** [comment]
Nudging this. I think alignment column numbers should not be shown by default as they are dependent on the collapse/expand state of nodes, and in general they do not correspond to any material reality

**Comment by cmdcolin** [comment]
I am a little worried about this as "something is lost" by hiding the coordinates entirely. it can help provide orientation especially in long alignments hundreds to thousands of amino acids long


 if I look at other tools for comparison for example, ncbi msa viewer (https://www.ncbi.nlm.nih.gov/projects/msaviewer/) displays coordinates by default, jalview displays coordinates by default and it has the ability to hide columns and rows, etc. 

is there any way to keep coordinates with our system? or just, in the ui, have a little tooltip to the user that the coordinates don't correspond to a physical coordinate. in the future, we can also work on making the per-row absolute coordinates display so that a user can get meaningful physical info too

**Comment by ihh** [comment]
The biggest problem is that the coordinates are not stable. They depend on which tree nodes are collapsed. This makes them actively misleading in my view. Column X does not refer to anything you can reliably come back to later unless you haven't touched the tree controls.

You say that JalView has column coords and also allows nodes to be collapsed; how does it handle this issue? If it has a solution then we can use that, if not then I'm not sure it's not much use as a comparison.

The original intent of ABrowse was to be an alignment viewer that overcame precisely this shortcoming of other alignment viewers (extraneous columns cluttering the alignment when you have deep phylogenies) by allowing the viewer to hide parts of the phylogeny. So I am resistant to the idea that just because other viewers do it, we should follow that model.

**Comment by ihh** [comment]
Specifically I think this app needs to have the following properties
- adding more sequences to a phylogeny does not corrupt the coordinate scheme of the alignment
- gappy rows of the alignment do not mess up the coordinate scheme
- gappy rows don't obscure regions of homology (this is the point of auto-hiding empty columns)

**Comment by ihh** [comment]
I would settle for a solution that kept the column numbers stable, even though this would mean the ruler no longer looked evenly-spaced when some nodes were collapsed

**Comment by cmdcolin** [comment]
I did a little brainstorming and tried to cross reference one other source of inspiration could be CLUSTALW.  CLUSTALW provides "character counts" for each row in it's (static) file output, so in this way, you can see the coordinates on a per row basis

we could adopt a similar approach and have a dynamically updated character count for each row pinned on the right side of the screen (and maybe on the left side too, so you can see a range). then another idea i had was to have a 'minimap' or 'overview scalebar' similar to jbrowse, so you can see left-to-right where you are in the alignment. if we had both of these, we could probably remove the coordinate bar at the top, as indeed, it can be misleading :)

**Comment by cmdcolin** [comment]
example of a mockup, based on example from "Clustal with numbers" here https://www.ebi.ac.uk/seqdb/confluence/display/JDSAT/Multiple+Sequence+Alignment+Tool+Output+Examples

![untitled(2)](https://github.com/GMOD/react-msaview/assets/6511937/e73d01d1-bfa3-4a41-aae5-33bf0c30c02f)

**Comment by ihh** [comment]
Yes I think this is acceptable. I think it'd be even better to have the numbers on the left hand side as well, to give a range (as you suggested).

**Comment by cmdcolin** [comment]
new version on https://gmod.github.io/react-msaview/ is now featuring the current master branch, which has the minimap + no column numbers. per-row numbers will probably be added as a next step

**Comment by cmdcolin** [comment]
(might have to clear local browser cache to get updated version e.g. ctrl+shift+r to refresh with cleared cache)

**Comment by cmdcolin** [comment]
effectively done now. follow ups about adding some amount of column number info is an add on
