### ISSUE TITLE
Deeper integration with JBrowse 2

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/react-msaview#43]
We already have the JBrowse 2 plugin, but it is not deeply integrated where you can navigate from a gene->MSA view.

The workflow for this undefined at the moment but I envision e.g. you right click a gene->launch a dialog box where you get the protein sequence of the gene you clicked and then additionally "recruit" evolutionarily distant or close gene sequences. This recruitment could fetch from external data sources or from a user-supplied database of protein sequences perhaps.

**Comment by cmdcolin** [comment]
from @ihh use case "[I want to] mouse over a nucleotide in a coding region of the genome (say a SNP in a VCF track) and see where on the protein structure it maps to."

**Comment by ihh** [comment]
Can we refine/split this issue? I believe that my original request (integration at the level of amino acid/row/column mouseover response) is partially implemented, though a deeper integration may be possible through e.g. a rudimentary pub/sub framework. This however is a bit distinct from the workflow described in the top comment above, which involves initiating some sort of homology search through the UI. So perhaps there are two issues here, and one is partially resolved (so maybe even three issues)? In any case the issue name should be edited to more precisely reflect the goal

**Comment by cmdcolin** [comment]
I created a 'roadmap issue' here https://github.com/orgs/GMOD/projects/8/views/1 to try to help address this. I have to sort of 'coordinate' this across a number of github repositories (jbrowse-components,react-msaview,jbrowse-plugin-msaview,jbrowse-plugin-protein3d) so i'm trying out this roadmap issue to help track. I haven't used the roadmap UI in github much, but can see how it goes

**Comment by cmdcolin** [comment]
you are welcome to append to it or edit it also.

**Comment by cmdcolin** [comment]
quite a bit has happened since this issue and it is indeed too vague. 

the project view link above helps with abstract notions and the different github repos will keep track of the individualized issues (hard cause it's spread across multiple repos but we have https://github.com/GMOD/jbrowse-plugin-msaview https://github.com/GMOD/react-msaview https://github.com/GMOD/jbrowse-plugin-protein3d)

**Comment by cmdcolin** [comment]
resisting the urge to make it a monorepo :) monorepos are troublesome in their own ways sometimes
