### ISSUE TITLE
"Virtual" scrollbars

### ISSUE THREAD

**Issue by carlesonielfa** [GMOD/react-msaview#48]
It would be nice to have scrollbars for the MSAView, since dragging the mouse for long visualizations can be very tedious
As mentioned in:
```

 added the click and drag scrolling behavior in https://github.com/GMOD/react-msaview/commit/bec03be02b9785d8a8c5042b95be581f9c50f305

could consider the virtual scrollbars still also

_Originally posted by @cmdcolin in https://github.com/GMOD/react-msaview/issues/6#issuecomment-854889902_
            
```

**Comment by cmdcolin** [comment]
thanks for making this issue...i will see what can be done. I am very used to used trackpad to scroll but understand that a mouse would have trouble with this

**Comment by cmdcolin** [comment]
I created some changes that now makes it so there is a "top level" horizontal scrollbar that you can click and drag

the current master branch here demonstrates
https://gmod.github.io/react-msaview/

sorry it took so long but if you're still using the app, lemme know what you think :)

**Comment by cmdcolin** [comment]
screenshot

![image](https://github.com/GMOD/react-msaview/assets/6511937/a2c9aca8-81ae-4115-ac45-097582512dde)

**Comment by cmdcolin** [comment]
maybe can close for now:)

**Comment by carlesonielfa** [comment]
Thanks for implementing the suggestion! It works great! ☺️
