### ISSUE TITLE
Highlight row and column during mouseover

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/react-msaview#52]
This would make a sort of cross hatch that may make it more clear what is being hovered

**Comment by MayaSatishRao** [comment]
@cmdcolin I wan to contribute to this issue. Can you please describe the issue in detail?

**Comment by cmdcolin** [comment]
this was actually fixed already

**Comment by cmdcolin** [comment]
@MayaSatishRao also, I appreciate the interest, but I noticed you posted this several times to our forums. I can't provide all the description you need, you need to do the research to understand the issues if you want to be involved. thanks, -colin
