### ISSUE TITLE
Added structures persist even when the MSA is changed

### ISSUE THREAD

**Issue by ihh** [GMOD/react-msaview#56]
In the demo, if you navigate to one of the examples (e.g. [PFAM SARS-CoV2 multi-stockholm](https://gmod.github.io/react-msaview/?data=%7B%22msaview%22%3A%7B%22data%22%3A%7B%22tree%22%3A%22%22%7D%2C%22id%22%3A%22FDan9bGReSfU7CMQhYTpS%22%2C%22minimized%22%3Afalse%2C%22type%22%3A%22MsaView%22%2C%22height%22%3A550%2C%22treeAreaWidth%22%3A400%2C%22treeWidth%22%3A300%2C%22rowHeight%22%3A20%2C%22scrollY%22%3A0%2C%22scrollX%22%3A0%2C%22resizeHandleWidth%22%3A5%2C%22blockSize%22%3A1000%2C%22mouseRow%22%3A0%2C%22mouseCol%22%3A5%2C%22selectedStructures%22%3A%5B%7B%22id%22%3A%22POLG_RHDVF%2F1288-1730%22%2C%22structure%22%3A%7B%22pdb%22%3A%221khw%22%2C%22startPos%22%3A37%2C%22endPos%22%3A479%7D%7D%5D%2C%22labelsAlignRight%22%3Afalse%2C%22colWidth%22%3A16%2C%22showBranchLen%22%3Atrue%2C%22bgColor%22%3Atrue%2C%22drawTree%22%3Atrue%2C%22drawNodeBubbles%22%3Atrue%2C%22highResScaleFactor%22%3A2%2C%22colorSchemeName%22%3A%22maeditor%22%2C%22msaFilehandle%22%3A%7B%22locationType%22%3A%22UriLocation%22%2C%22uri%22%3A%22https%3A%2F%2Fihh.github.io%2Fabrowse%2Fbuild%2Fpfam-cov2.stock%22%7D%2C%22currentAlignment%22%3A0%2C%22collapsed%22%3A%5B%5D%2C%22boxTracks%22%3A%5B%5D%2C%22turnedOffTracks%22%3A%7B%7D%2C%22annotatedRegions%22%3A%5B%5D%7D%2C%22nglSelection%22%3A%22%22%7D#)), add a structure (e.g. POLG_RHDVF), then click on the folder icon at top left and navigate to another example (e.g. [Lysine stockholm file](https://gmod.github.io/react-msaview/?data=%7B%22msaview%22%3A%7B%22data%22%3A%7B%22tree%22%3A%22%22%7D%2C%22id%22%3A%22FDan9bGReSfU7CMQhYTpS%22%2C%22minimized%22%3Afalse%2C%22type%22%3A%22MsaView%22%2C%22height%22%3A550%2C%22treeAreaWidth%22%3A400%2C%22treeWidth%22%3A300%2C%22rowHeight%22%3A20%2C%22scrollY%22%3A0%2C%22scrollX%22%3A0%2C%22resizeHandleWidth%22%3A5%2C%22blockSize%22%3A1000%2C%22selectedStructures%22%3A%5B%7B%22id%22%3A%22POLG_RHDVF%2F1288-1730%22%2C%22structure%22%3A%7B%22pdb%22%3A%221khw%22%2C%22startPos%22%3A37%2C%22endPos%22%3A479%7D%7D%5D%2C%22labelsAlignRight%22%3Afalse%2C%22colWidth%22%3A16%2C%22showBranchLen%22%3Atrue%2C%22bgColor%22%3Atrue%2C%22drawTree%22%3Atrue%2C%22drawNodeBubbles%22%3Atrue%2C%22highResScaleFactor%22%3A2%2C%22colorSchemeName%22%3A%22maeditor%22%2C%22msaFilehandle%22%3A%7B%22locationType%22%3A%22UriLocation%22%2C%22uri%22%3A%22https%3A%2F%2Fjbrowse.org%2Fgenomes%2Fmultiple_sequence_alignments%2FLysine.stock%22%7D%2C%22currentAlignment%22%3A0%2C%22collapsed%22%3A%5B%5D%2C%22boxTracks%22%3A%5B%5D%2C%22turnedOffTracks%22%3A%7B%7D%2C%22annotatedRegions%22%3A%5B%5D%7D%2C%22nglSelection%22%3A%22%22%7D#)), then the PDB structure that was added for the first example remains visible throughout. It should either be cleared, perhaps with a warning/confirmation dialog, or a warning should be displayed that the structure being visualized is not one of the structures in the MSA currently being shown.

**Comment by cmdcolin** [comment]
can confirm. i can make the app can more thoroughly 'clear the state' when it changes files
