### ISSUE TITLE
Rendering of protein domains

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/react-msaview#72]
a workflow can be done to dynamically or statically load a list of domain annotations (e.g. interproscan on every row of the MSA)

this can then be displayed

one challenge is that the domains/protein features can be overlapping, but we can sort by length of the sequences so that small features are always displayed on top of larger features

another ongoing challenge would be making proper domain labels or legends is sort of tricky

here is an example of this (works on main)

![image](https://github.com/GMOD/react-msaview/assets/6511937/25473ee0-d321-450e-bd17-24d40d6b173a)

we can make a feature that lets users choose which domains they want to display also

![image](https://github.com/GMOD/react-msaview/assets/6511937/ea1d6919-3d58-49b1-bc8b-86d70701361d)

the above data is real and manually collected from running interproscan on all the rows of the sars-cov2 stockholm file, but it needs some work to make it dynamic or statically loadable

this is a general effort that tries to display the data on a per-row basis instead of the previous method that "mapped a specific row's annotation to a box track on top"

**Comment by cmdcolin** [comment]
notably, the letters can be rendered on top of the domains, so you can get that complementary information. i initially conceived of it as a totally separate rendering mode but i think adding letters as an overlay is important in some cases that helps a user determine e.g. "why didn't interpro predict X domain here"...

**Comment by ihh** [comment]
I do like this idea but it does raise an interesting question: should we also do this in JBrowse? Which would add more value? Seems like the JBrowse one would be more generally useful, perhaps more complicated due to domains split by introns, but perhaps also implementation could leverage existing feature-rendering machinery

**Comment by cmdcolin** [comment]
I would probably keep prioritizing the msaview version, I can try and get a demo soon for you try try out. I think it can actually launch a interproscan on the fly via EBI rest api for all the msa sequences, which i think would work well for modest numbers of sequences. For larger data could imagine running it offline. But i agree that a jbrowse track would be great too, and could probably be added!

**Comment by cmdcolin** [comment]
this was now actually merged and deployed. there could be some additional methods to add this to jbrowse itself though.

example of a uniprot domains track from our ucsc demo https://jbrowse.org/demos/ucsc2/?session=share-yDF6eI-%2B5p&password=UrOGP
